// <auto-generated />
using System;
using AntalyaOtelApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AntalyaOtelApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AntalyaOtelApi.Models.Musteri", b =>
                {
                    b.Property<int>("MusteriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MusteriId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MusteriId");

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("AntalyaOtelApi.Models.Oda", b =>
                {
                    b.Property<int>("OdaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OdaId"));

                    b.Property<int>("Kat")
                        .HasColumnType("int");

                    b.Property<bool>("Musaitmi")
                        .HasColumnType("bit");

                    b.Property<int>("OdaNo")
                        .HasColumnType("int");

                    b.Property<int>("OdaTipId")
                        .HasColumnType("int");

                    b.HasKey("OdaId");

                    b.ToTable("Odalar");

                    b.HasData(
                        new
                        {
                            OdaId = 1,
                            Kat = 1,
                            Musaitmi = false,
                            OdaNo = 101,
                            OdaTipId = 1
                        },
                        new
                        {
                            OdaId = 2,
                            Kat = 1,
                            Musaitmi = false,
                            OdaNo = 102,
                            OdaTipId = 1
                        },
                        new
                        {
                            OdaId = 3,
                            Kat = 2,
                            Musaitmi = false,
                            OdaNo = 201,
                            OdaTipId = 2
                        },
                        new
                        {
                            OdaId = 4,
                            Kat = 2,
                            Musaitmi = false,
                            OdaNo = 202,
                            OdaTipId = 2
                        },
                        new
                        {
                            OdaId = 5,
                            Kat = 3,
                            Musaitmi = false,
                            OdaNo = 301,
                            OdaTipId = 3
                        });
                });

            modelBuilder.Entity("AntalyaOtelApi.Models.OdaTipi", b =>
                {
                    b.Property<int>("OdaTipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OdaTipId"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GunlukFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OdaTipId");

                    b.ToTable("OdaTipleri");

                    b.HasData(
                        new
                        {
                            OdaTipId = 1,
                            Aciklama = "1 Çift Kişilik Yatak, Şehir Manzaralı",
                            GunlukFiyat = 1000m,
                            TipAdi = "Standart"
                        },
                        new
                        {
                            OdaTipId = 2,
                            Aciklama = "Geniş Balkon, Deniz Manzaralı, Jakuzili",
                            GunlukFiyat = 2500m,
                            TipAdi = "Deluxe"
                        },
                        new
                        {
                            OdaTipId = 3,
                            Aciklama = "Özel Teras, Özel Havuz, Ultra Lüks",
                            GunlukFiyat = 7500m,
                            TipAdi = "Kral Dairesi"
                        });
                });

            modelBuilder.Entity("AntalyaOtelApi.Models.Rezervasyon", b =>
                {
                    b.Property<int>("RezervasyonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RezervasyonId"));

                    b.Property<DateTime>("CikisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GirisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IptalEdildi")
                        .HasColumnType("bit");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<int>("OdaId")
                        .HasColumnType("int");

                    b.Property<decimal>("ToplamTutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("RezervasyonId");

                    b.ToTable("Rezervasyonlar");
                });
#pragma warning restore 612, 618
        }
    }
}
